/* Fixed-purpose Onion MainUI handoff bridge.
 *
 * This binary is installed setuid-root in /tmp by the root-owned startup
 * helper. It accepts no arguments and can only release MainUI for the exact
 * MiyooFin queue generated by onion-remote-launch.sh.
 */
#define _GNU_SOURCE
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#define EXPECTED_ONION_UID 1000
#define QUEUE_PATH "/tmp/cmd_to_run.sh"
#define MAINUI_PATH "/mnt/SDCARD/miyoo/app/MainUI"
#define QUEUE_MAX 4096

static int fail(const char *message)
{
    fprintf(stderr, "miyoofin-mainui-handoff: %s\n", message);
    return 1;
}

static int line_has_prefix(const char *line, const char *prefix)
{
    return strncmp(line, prefix, strlen(prefix)) == 0;
}

static int decimal_suffix(const char *line, const char *prefix)
{
    const char *p = line + strlen(prefix);
    if (*p == '\0') return 0;
    while (*p != '\0') {
        if (*p < '0' || *p > '9') return 0;
        ++p;
    }
    return 1;
}

static int validate_queue(void)
{
    int fd = open(QUEUE_PATH, O_RDONLY | O_CLOEXEC | O_NOFOLLOW);
    if (fd < 0) return fail("staged launch file is unavailable");

    struct stat st;
    if (fstat(fd, &st) != 0 || !S_ISREG(st.st_mode)) {
        close(fd);
        return fail("staged launch file is not a regular file");
    }
    if (st.st_size <= 0 || st.st_size >= QUEUE_MAX) {
        close(fd);
        return fail("staged launch file has an invalid size");
    }

    char content[QUEUE_MAX];
    ssize_t size = read(fd, content, sizeof(content) - 1);
    close(fd);
    if (size <= 0 || size >= (ssize_t)sizeof(content))
        return fail("staged launch file could not be read");
    content[size] = '\0';

    char *lines[16] = {0};
    size_t count = 0;
    char *cursor = content;
    while (count < 16) {
        lines[count++] = cursor;
        char *newline = strchr(cursor, '\n');
        if (!newline) break;
        *newline = '\0';
        cursor = newline + 1;
        if (*cursor == '\0') break;
    }
    if (count < 8 || (count == 16 && strchr(lines[15], '\n') != NULL))
        return fail("staged launch file has malformed line structure");

    if (strcmp(lines[0], "#!/bin/sh") != 0 ||
        !line_has_prefix(lines[1], "LEASE=/tmp/.miyoofin-onion-remote-lease.") ||
        !decimal_suffix(lines[1], "LEASE=/tmp/.miyoofin-onion-remote-lease.") ||
        !decimal_suffix(lines[2], "DEADLINE=") ||
        strcmp(lines[3], "[ -f \"$LEASE\" ] || exit 75") != 0 ||
        strcmp(lines[4], "now=$(date +%s)") != 0 ||
        strcmp(lines[5], "[ \"$now\" -lt \"$DEADLINE\" ] || { rm -f \"$LEASE\"; exit 75; }") != 0 ||
        strcmp(lines[6], "rm -f \"$LEASE\"") != 0 ||
        strcmp(lines[7], "cd '/mnt/SDCARD/App/MiyooFin' || exit 1") != 0)
        return fail("staged launch file is not an approved MiyooFin handoff");

    size_t final = 8;
    if (final < count && strcmp(lines[final], "export MIYOOFIN_TELEMETRY=1") == 0)
        ++final;
    if (final + 1 != count ||
        strcmp(lines[final], "exec '/mnt/SDCARD/App/MiyooFin/launch.sh'") != 0)
        return fail("staged launch command is not an approved MiyooFin form");
    return 0;
}

static int process_is_mainui(const char *pid_name)
{
    char path[PATH_MAX];
    snprintf(path, sizeof(path), "/proc/%s/comm", pid_name);
    int fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) return 0;
    char comm[32] = {0};
    ssize_t n = read(fd, comm, sizeof(comm) - 1);
    close(fd);
    if (n <= 0) return 0;
    comm[strcspn(comm, "\n")] = '\0';
    if (strcmp(comm, "MainUI") != 0) return 0;

    snprintf(path, sizeof(path), "/proc/%s/status", pid_name);
    fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) return 0;
    char status[4096] = {0};
    n = read(fd, status, sizeof(status) - 1);
    close(fd);
    if (n <= 0) return 0;
    char *uid_line = strstr(status, "\nUid:");
    if (uid_line) {
        ++uid_line;
    } else {
        uid_line = strstr(status, "Uid:");
    }
    unsigned long uid = 1;
    if (!uid_line || sscanf(uid_line, "Uid:\t%lu", &uid) != 1 || uid != 0)
        return 0;

    char exe[PATH_MAX];
    snprintf(path, sizeof(path), "/proc/%s/exe", pid_name);
    ssize_t exe_size = readlink(path, exe, sizeof(exe) - 1);
    if (exe_size > 0) {
        exe[exe_size] = '\0';
        return strcmp(exe, MAINUI_PATH) == 0;
    }

    /* The process name is the fallback identity on this Onion build:
     * /proc/<pid>/exe is hidden from the ordinary inspection shell. */
    snprintf(path, sizeof(path), "/proc/%s/cmdline", pid_name);
    fd = open(path, O_RDONLY | O_CLOEXEC);
    if (fd < 0) return 0;
    char cmdline[64] = {0};
    n = read(fd, cmdline, sizeof(cmdline) - 1);
    close(fd);
    return (n == 8 && memcmp(cmdline, "./MainUI", 8) == 0) ||
           (n == 9 && memcmp(cmdline, "./MainUI\0", 9) == 0);
}

static int find_mainui(pid_t *result)
{
    DIR *dir = opendir("/proc");
    if (!dir) return fail("cannot inspect /proc");
    pid_t found = -1;
    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL) {
        const char *name = entry->d_name;
        if (*name == '\0') continue;
        int numeric = 1;
        for (const char *p = name; *p; ++p)
            if (*p < '0' || *p > '9') numeric = 0;
        if (!numeric || !process_is_mainui(name)) continue;
        pid_t pid = (pid_t)strtol(name, NULL, 10);
        if (found != -1) {
            closedir(dir);
            return fail("multiple validated MainUI processes exist");
        }
        found = pid;
    }
    closedir(dir);
    if (found == -1) return fail("no validated MainUI process exists");
    *result = found;
    return 0;
}

int main(int argc, char **argv)
{
    (void)argv;
    if (argc != 1)
        return fail("arguments are not accepted");
    if (getuid() != EXPECTED_ONION_UID)
        return fail("caller is not the onion account");
    if (geteuid() != 0)
        return fail("helper is not running setuid-root");
    if (getenv("PATH") != NULL) unsetenv("PATH");
    if (validate_queue() != 0) return 1;

    pid_t mainui = -1;
    if (find_mainui(&mainui) != 0) return 1;
    if (kill(mainui, SIGTERM) != 0) return fail("validated MainUI SIGTERM failed");
    return 0;
}
