#include "OfflinePlaybackJournal.hpp"
#include <cstdio>
#include <cerrno>
#include <sys/stat.h>
#include <unistd.h>
namespace miyoofin { namespace { bool dirs(const std::string&p){for(size_t i=1;i<=p.size();++i)if(i==p.size()||p[i]=='/'){std::string d=p.substr(0,i);if(!d.empty()&&mkdir(d.c_str(),0755)&&errno!=EEXIST)return false;}return true;} bool safe(const std::string&s){return !s.empty()&&s.find_first_of("\n\r=")==std::string::npos;} }
std::string OfflinePlaybackJournal::path(const std::string&r,const std::string&s){return r+"/offline/"+s+"/playback-journal.v1";}
bool OfflinePlaybackJournal::load(const std::string&p,std::vector<OfflinePlaybackEntry>&o,std::string*e){FILE*f=fopen(p.c_str(),"r");if(!f){if(e)*e="not found";return false;}char b[1024];if(!fgets(b,sizeof b,f)||std::string(b)!="MFOPJ=1\n"){fclose(f);if(e)*e="invalid journal";return false;}OfflinePlaybackEntry x;while(fgets(b,sizeof b,f)){std::string l=b;if(l=="end\n"){if(!safe(x.itemId)){fclose(f);if(e)*e="invalid journal";return false;}o.push_back(x);x={};continue;}size_t q=l.find('=');if(q==std::string::npos)continue;std::string k=l.substr(0,q),v=l.substr(q+1);if(!v.empty()&&v.back()=='\n')v.pop_back();if(k=="item")x.itemId=v;else if(k=="type")x.itemType=v;else if(k=="base")x.baseServerTicks=std::strtoll(v.c_str(),nullptr,10);else if(k=="final")x.finalTicks=std::strtoll(v.c_str(),nullptr,10);else if(k=="time")x.localTimestamp=std::strtoull(v.c_str(),nullptr,10);else if(k=="conflict")x.conflict=v=="1";else if(k=="missing")x.serverMissing=v=="1";}fclose(f);return true;}
bool OfflinePlaybackJournal::save(const std::string&p,const std::vector<OfflinePlaybackEntry>&v,std::string*e){size_t q=p.find_last_of('/');if(q!=std::string::npos&&!dirs(p.substr(0,q))){if(e)*e="mkdir failed";return false;}std::string t=p+".tmp";FILE*f=fopen(t.c_str(),"w");if(!f){if(e)*e="write failed";return false;}fprintf(f,"MFOPJ=1\n");for(const auto&x:v)fprintf(f,"item=%s\ntype=%s\nbase=%lld\nfinal=%lld\ntime=%llu\nconflict=%d\nmissing=%d\nend\n",x.itemId.c_str(),x.itemType.c_str(),(long long)x.baseServerTicks,(long long)x.finalTicks,(unsigned long long)x.localTimestamp,x.conflict,x.serverMissing);bool ok=fflush(f)==0&&fsync(fileno(f))==0&&fclose(f)==0&&rename(t.c_str(),p.c_str())==0;if(!ok){remove(t.c_str());if(e)*e="write failed";}return ok;}
bool OfflinePlaybackJournal::upsert(const std::string&p,const OfflinePlaybackEntry&x,std::string*e){if(!safe(x.itemId)){if(e)*e="invalid item";return false;}std::vector<OfflinePlaybackEntry>v;std::string ignored;load(p,v,&ignored);for(auto&i:v)if(i.itemId==x.itemId){i=x;return save(p,v,e);}v.push_back(x);return save(p,v,e);}
bool OfflinePlaybackJournal::discardMissing(const std::string&p,const std::string&id,std::string*e){std::vector<OfflinePlaybackEntry> v;if(!load(p,v,e))return false;for(auto it=v.begin();it!=v.end();++it)if(it->itemId==id&&it->serverMissing){v.erase(it);return save(p,v,e);}if(e)*e="entry is not permanently missing";return false;}
OfflineJournalSyncStats syncOfflinePlaybackEntries(std::vector<OfflinePlaybackEntry>& entries,const std::function<OfflineJournalRequestStatus(const OfflinePlaybackEntry&,std::int64_t&)>& fetch,const std::function<OfflineJournalRequestStatus(const OfflinePlaybackEntry&)>& submit){OfflineJournalSyncStats stats;for(auto it=entries.begin();it!=entries.end();){if(it->conflict||it->serverMissing){++it;continue;}std::int64_t server=0;OfflineJournalRequestStatus got=fetch(*it,server);if(got==OfflineJournalRequestStatus::Missing){it->serverMissing=true;stats.changed=true;++it;continue;}if(got!=OfflineJournalRequestStatus::Success){stats.retry=true;stats.unauthorized|=got==OfflineJournalRequestStatus::Unauthorized;++it;continue;}if(decideOfflineSync(it->baseServerTicks,server,true)==OfflineSyncDecision::Conflict){it->conflict=true;stats.changed=true;++stats.conflicts;++it;continue;}OfflineJournalRequestStatus pushed=submit(*it);if(pushed==OfflineJournalRequestStatus::Success){it=entries.erase(it);stats.changed=true;++stats.pushed;continue;}stats.retry=true;stats.unauthorized|=pushed==OfflineJournalRequestStatus::Unauthorized;++it;}return stats;}
}
