#include "DownloadManager.hpp"
#include "../net/JellyfinApi.hpp"
#include "../net/RouteRequest.hpp"
#include "../cache/OfflineCatalog.hpp"
#include "../cache/LibraryCache.hpp"
#include "DownloadSupport.hpp"
#include "../app/UiDiagnostics.hpp"

namespace miyoofin {

DownloadPlan DownloadManager::makePlan(const std::vector<DownloadItem>&in)const{DownloadPlan p;p.filesystemFreeBytes=freeBytes();p.usableFreeBytes=p.filesystemFreeBytes>DOWNLOAD_SAFETY_RESERVE?p.filesystemFreeBytes-DOWNLOAD_SAFETY_RESERVE:0;auto s=snapshot();std::map<std::string,bool>seen;p.sizeKnown=true;for(auto i:in)if(seen.emplace(i.itemId,true).second){auto old=std::find_if(s.items.begin(),s.items.end(),[&](const DownloadItem&x){return x.itemId==i.itemId;});if(old!=s.items.end()){i.downloadedBytes=old->downloadedBytes;if(!i.hlsStorage&&old->expectedSize)i.expectedSize=old->expectedSize;}std::uint64_t planned=0;if(!plannedDownloadBytes(i,planned)){p.sizeKnown=false;p.items.push_back(i);continue;}i.expectedSize=planned;p.items.push_back(i);p.totalSourceBytes=saturatingAdd(p.totalSourceBytes,planned);p.alreadyPresentBytes=saturatingAdd(p.alreadyPresentBytes,std::min(i.downloadedBytes,planned));if(old==s.items.end())p.additionalRequiredBytes=saturatingAdd(p.additionalRequiredBytes,i.downloadedBytes>=planned?0:planned-i.downloadedBytes);}p.alreadyReservedBytes=s.reservedBytes;p.usableFreeBytes=p.usableFreeBytes>s.reservedBytes?p.usableFreeBytes-s.reservedBytes:0;p.canFit=p.sizeKnown&&p.additionalRequiredBytes<=p.usableFreeBytes;if(!p.sizeKnown)p.error="Estimated HLS size unavailable";else if(!p.canFit)p.error="Not enough space";return p;}
std::uint64_t DownloadManager::requestPlan(const std::vector<MediaItem>&items){
    std::vector<DownloadItem> provisional;
    for(const auto&m:items){DownloadItem i;i.itemId=m.id;i.itemType=m.type;i.title=m.title;i.runtimeTicks=m.runTimeTicks;i.hlsStorage=true;provisional.push_back(i);}
    DownloadPlan estimate;
    {
        UiDiagnostics::Scope scope("DownloadManager::requestPlan snapshot/filesystem estimate",false);
        estimate=makePlan(provisional);
    }
    std::unique_lock<std::mutex>l(m_mutex,std::defer_lock);
    {
        UiDiagnostics::Scope scope("DownloadManager::requestPlan mutex wait",false);
        l.lock();
    }
    std::uint64_t id=m_nextPlanId++;DownloadPlanSnapshot s;s.id=id;s.state=DownloadPlanState::Planning;s.itemCount=items.size();s.plan=estimate;m_plans[id]=s;m_planJobs.push_back({id,m_generation,m_session,items,"","",{}, {}});m_planWake.notify_one();return id;
}
std::uint64_t DownloadManager::requestSeriesPlan(const std::string&seriesId){MediaItem series;series.id=seriesId;return requestSeriesPlan(series);}
std::uint64_t DownloadManager::requestSeasonPlan(const std::string&seriesId,const std::string&seasonId){MediaItem series,season;series.id=seriesId;season.id=seasonId;season.seriesId=seriesId;return requestSeasonPlan(series,season);}
std::uint64_t DownloadManager::requestSeriesPlan(const MediaItem&series){OfflineCatalogSnapshot cache;std::vector<MediaItem> cached;if(OfflineCatalog::load(OfflineCatalog::cachePath("cache",LibraryCache::scopeKey(m_session.serverUrl,m_session.userId)),cache)){auto it=cache.seasonsBySeries.find(series.id);if(it!=cache.seasonsBySeries.end())for(const auto&season:it->second){auto eps=cache.episodesBySeason.find(season.id);if(eps==cache.episodesBySeason.end()){cached.clear();break;}cached.insert(cached.end(),eps->second.begin(),eps->second.end());}}std::vector<DownloadItem> provisional;for(const auto&m:cached){DownloadItem i;i.itemId=m.id;i.runtimeTicks=m.runTimeTicks;i.hlsStorage=true;provisional.push_back(i);}DownloadPlan estimate=cached.empty()?DownloadPlan{}:makePlan(provisional);std::lock_guard<std::mutex>l(m_mutex);std::uint64_t id=m_nextPlanId++;DownloadPlanSnapshot s;s.id=id;s.state=DownloadPlanState::Planning;s.itemCount=cached.size();s.plan=estimate;m_plans[id]=s;m_planJobs.push_back({id,m_generation,m_session,{},series.id,"",series,{}});m_planWake.notify_one();return id;}
std::uint64_t DownloadManager::requestSeasonPlan(const MediaItem&series,const MediaItem&season){OfflineCatalogSnapshot cache;std::vector<MediaItem> cached;auto path=OfflineCatalog::cachePath("cache",LibraryCache::scopeKey(m_session.serverUrl,m_session.userId));if(OfflineCatalog::load(path,cache)){auto it=cache.episodesBySeason.find(season.id);if(it!=cache.episodesBySeason.end())cached=it->second;}std::vector<DownloadItem> provisional;for(const auto&m:cached){DownloadItem i;i.itemId=m.id;i.runtimeTicks=m.runTimeTicks;i.hlsStorage=true;provisional.push_back(i);}DownloadPlan estimate=cached.empty()?DownloadPlan{}:makePlan(provisional);std::lock_guard<std::mutex>l(m_mutex);std::uint64_t id=m_nextPlanId++;DownloadPlanSnapshot s;s.id=id;s.state=DownloadPlanState::Planning;s.itemCount=cached.size();s.plan=estimate;m_plans[id]=s;m_planJobs.push_back({id,m_generation,m_session,{},series.id,season.id,series,season});m_planWake.notify_one();return id;}
DownloadPlanSnapshot DownloadManager::planSnapshot(std::uint64_t id)const{UiDiagnostics::Scope scope("DownloadManager::planSnapshot mutex wait");std::lock_guard<std::mutex>l(m_mutex);auto it=m_plans.find(id);return it==m_plans.end()?DownloadPlanSnapshot{}:it->second;}
bool DownloadManager::tryPlanSnapshot(std::uint64_t id,DownloadPlanSnapshot&snapshot)const{std::unique_lock<std::mutex>l(m_mutex,std::try_to_lock);if(!l.owns_lock())return false;auto it=m_plans.find(id);snapshot=it==m_plans.end()?DownloadPlanSnapshot{}:it->second;return true;}

void DownloadManager::planner(){for(;;){PlanJob job;{std::unique_lock<std::mutex>l(m_mutex);m_planWake.wait(l,[&]{return m_stop||!m_planJobs.empty();});if(m_stop)return;job=std::move(m_planJobs.front());m_planJobs.pop_front();}std::vector<MediaItem> media=job.items,seasons;std::map<std::string,std::vector<MediaItem> > hierarchy;std::string error;if(!job.seasonId.empty()){if(RouteRequest(job.session).run([&](const std::string&base){return JellyfinApi::getEpisodes(base,job.session.accessToken,job.session.userId,job.session.deviceId,job.seriesId,job.seasonId,media,error);},error)){MediaItem season=job.season;season.id=job.seasonId;season.seriesId=job.seriesId;seasons.push_back(season);hierarchy[job.seasonId]=media;}}else if(!job.seriesId.empty()){if(RouteRequest(job.session).run([&](const std::string&base){return JellyfinApi::getSeasons(base,job.session.accessToken,job.session.userId,job.session.deviceId,job.seriesId,seasons,error);},error))for(const auto&season:seasons){std::vector<MediaItem> episodes;if(!RouteRequest(job.session).run([&](const std::string&base){return JellyfinApi::getEpisodes(base,job.session.accessToken,job.session.userId,job.session.deviceId,job.seriesId,season.id,episodes,error);},error))break;hierarchy[season.id]=episodes;media.insert(media.end(),episodes.begin(),episodes.end());}}if(error.empty()&&!job.seriesId.empty()){MediaItem series=job.series;series.id=job.seriesId;if(series.title.empty())for(const auto&a:hierarchy)if(!a.second.empty()){series.title=a.second.front().seriesName;break;}OfflineCatalog::storeDiscoveredHierarchy(OfflineCatalog::cachePath("cache",LibraryCache::scopeKey(job.session.serverUrl,job.session.userId)),series,seasons,hierarchy,true,nullptr);}std::vector<DownloadItem> out;std::set<std::string> seen;for(const auto&m:media){if(!seen.insert(m.id).second)continue;std::vector<DownloadMediaSource> sources;if(!RouteRequest(job.session).run([&](const std::string&base){return JellyfinApi::getDownloadMediaSources(base,job.session.accessToken,job.session.userId,job.session.deviceId,m.id,sources,error);},error)||sources.empty()){if(error.empty())error="No downloadable media source";break;}out.push_back(makeDownloadItem(m,sources.front()));}DownloadPlan calculated; if(error.empty()) calculated=makePlan(out);std::lock_guard<std::mutex>l(m_mutex);auto it=m_plans.find(job.id);if(it==m_plans.end()||job.generation!=m_generation)continue;it->second.itemCount=out.size();if(!error.empty()){it->second.state=DownloadPlanState::Error;it->second.plan.error=error;}else{it->second.plan=calculated;it->second.state=calculated.error.empty()?DownloadPlanState::Ready:DownloadPlanState::Error;}}}

} // namespace miyoofin
