#include "DownloadStore.hpp"
#include "../cache/LibraryCache.hpp"
#include <cstdio>
#include <cerrno>
#include <cstring>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>
#include <cctype>
#include <set>

namespace miyoofin { namespace {
bool safeId(const std::string&s){ if(s.empty()||s.size()>255)return false; for(unsigned char c:s)if(!(std::isalnum(c)||c=='-'||c=='_'||c=='.'))return false; return true; }
bool mkdirs(const std::string&p){ for(size_t i=1;i<=p.size();++i)if(i==p.size()||p[i]=='/'){std::string d=p.substr(0,i);if(!d.empty()&&::mkdir(d.c_str(),0755)&&errno!=EEXIST)return false;} return true; }
bool fileSize(const std::string&p,std::uint64_t &out){struct stat st{};if(::stat(p.c_str(),&st)||st.st_size<0)return false;out=(std::uint64_t)st.st_size;return true;}
std::string enc(const std::string&s){static const char*x="0123456789ABCDEF";std::string o;for(unsigned char c:s){if((c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c=='-'||c=='_')o+=c;else{o+='%';o+=x[c>>4];o+=x[c&15];}}return o;}
int hx(char c){return c>='0'&&c<='9'?c-'0':c>='A'&&c<='F'?c-'A'+10:c>='a'&&c<='f'?c-'a'+10:-1;}
std::string dec(const std::string&s){std::string o;for(size_t i=0;i<s.size();++i)if(s[i]=='%'&&i+2<s.size()&&hx(s[i+1])>=0&&hx(s[i+2])>=0){o+=(char)(hx(s[i+1])*16+hx(s[i+2]));i+=2;}else o+=s[i];return o;}
bool atomic(const std::string&p,const std::string&body){auto q=p.find_last_of('/');if(q!=std::string::npos&&!mkdirs(p.substr(0,q)))return false;std::string t=p+".tmp";FILE*f=std::fopen(t.c_str(),"wb");if(!f)return false;bool ok=std::fwrite(body.data(),1,body.size(),f)==body.size()&&std::fflush(f)==0&&::fsync(fileno(f))==0&&std::fclose(f)==0;if(!ok||std::rename(t.c_str(),p.c_str())){std::remove(t.c_str());return false;}return true;}
std::string get(const std::string&b,const char*k){std::string p=std::string(k)+"=";size_t i=b.find(p);if(i==std::string::npos|| (i&&b[i-1]!='\n'))return {};i+=p.size();size_t e=b.find('\n',i);return dec(b.substr(i,e==std::string::npos?std::string::npos:e-i));}
void put(std::string&b,const char*k,const std::string&v){b+=k;b+='=';b+=enc(v);b+='\n';} void pu(std::string&b,const char*k,std::uint64_t v){b+=k;b+='=';b+=std::to_string(v);b+='\n';}
bool num(const std::string&s,std::uint64_t&o){if(s.empty())return false;char*e=nullptr;errno=0;unsigned long long x=std::strtoull(s.c_str(),&e,10);if(errno||*e)return false;o=x;return true;}
std::string serialize(const DownloadItem&i){std::string b=i.hlsStorage?"MFDM=2\n":"MFDM=1\n";put(b,"item",i.itemId);put(b,"type",i.itemType);put(b,"title",i.title);put(b,"series",i.seriesId);put(b,"series_name",i.seriesName);put(b,"season",i.seasonId);put(b,"season_name",i.seasonName);put(b,"source",i.mediaSourceId);put(b,"available_source",i.availableMediaSourceId);put(b,"container",i.container);put(b,"etag",i.sourceEtag);put(b,"available_etag",i.availableSourceEtag);put(b,"video",i.videoCodec);put(b,"audio",i.audioCodec);put(b,"error",i.lastError);pu(b,"size",i.expectedSize);pu(b,"available_size",i.availableSize);pu(b,"chunk",i.chunkSize);pu(b,"downloaded",i.downloadedBytes);pu(b,"state",(unsigned)i.state);pu(b,"runtime",i.runtimeTicks<0?0:i.runtimeTicks);pu(b,"position",i.playbackPositionTicks<0?0:i.playbackPositionTicks);pu(b,"season_no",i.seasonNumber);pu(b,"episode_no",i.episodeNumber);pu(b,"width",i.width);pu(b,"height",i.height);pu(b,"bitrate",i.bitrate);pu(b,"created",i.createdAt);pu(b,"updated",i.updatedAt);pu(b,"flags",(i.localOnly?1:0)|(i.updateAvailable?2:0)|(i.externalSubtitles?4:0));if(i.hlsStorage){pu(b,"segments",i.hlsSegmentCount);put(b,"profile",i.hlsProfile);}return b;}
bool parse(const std::string&b,DownloadItem&i){bool hls=b.rfind("MFDM=2\n",0)==0;if(!hls&&b.rfind("MFDM=1\n",0))return false;i={};i.hlsStorage=hls;i.itemId=get(b,"item");if(!safeId(i.itemId))return false;i.itemType=get(b,"type");i.title=get(b,"title");i.seriesId=get(b,"series");i.seriesName=get(b,"series_name");i.seasonId=get(b,"season");i.seasonName=get(b,"season_name");i.mediaSourceId=get(b,"source");i.availableMediaSourceId=get(b,"available_source");i.container=get(b,"container");i.sourceEtag=get(b,"etag");i.availableSourceEtag=get(b,"available_etag");i.videoCodec=get(b,"video");i.audioCodec=get(b,"audio");i.lastError=get(b,"error");std::uint64_t x=0; if(!num(get(b,"size"),i.expectedSize)||!num(get(b,"chunk"),i.chunkSize)||!num(get(b,"downloaded"),i.downloadedBytes)||!num(get(b,"state"),x)||x>(unsigned)DownloadState::NoSpace)return false;num(get(b,"available_size"),i.availableSize);i.state=(DownloadState)x;num(get(b,"runtime"),x);i.runtimeTicks=x;num(get(b,"position"),x);i.playbackPositionTicks=x;num(get(b,"season_no"),x);i.seasonNumber=x;num(get(b,"episode_no"),x);i.episodeNumber=x;num(get(b,"width"),x);i.width=x;num(get(b,"height"),x);i.height=x;num(get(b,"bitrate"),i.bitrate);num(get(b,"created"),i.createdAt);num(get(b,"updated"),i.updatedAt);num(get(b,"flags"),x);i.localOnly=x&1;i.updateAvailable=x&2;i.externalSubtitles=x&4;if(hls&&!num(get(b,"segments"),i.hlsSegmentCount))return false;i.hlsProfile=get(b,"profile");return i.chunkSize>0;}
bool read(const std::string&p,std::string&b){FILE*f=std::fopen(p.c_str(),"rb");if(!f)return false;char q[4096];size_t n;while((n=std::fread(q,1,sizeof q,f)))b.append(q,n);bool ok=!std::ferror(f);std::fclose(f);return ok;}
}
std::string DownloadStore::scopeKey(const std::string&a,const std::string&b){return LibraryCache::scopeKey(a,b);} std::string DownloadStore::scopePath(const std::string&s)const{return m_root+"/"+s;} std::string DownloadStore::itemPath(const std::string&s,const std::string&i)const{return scopePath(s)+"/items/"+i;} std::string DownloadStore::manifestPath(const std::string&s,const std::string&i)const{return itemPath(s,i)+"/manifest.v2";} std::string DownloadStore::chunkPath(const std::string&s,const std::string&i,std::uint64_t n,bool part)const{char b[48];std::snprintf(b,sizeof b,"chunk-%06llu.%s",(unsigned long long)n,part?"part":"bin");return itemPath(s,i)+"/chunks/"+b;} std::string DownloadStore::segmentPath(const std::string&s,const std::string&i,std::uint64_t n,bool part)const{char b[32];std::snprintf(b,sizeof b,"%06llu.%s",(unsigned long long)n,part?"part":"bin");return itemPath(s,i)+"/segments/"+b;} bool DownloadStore::ensureHlsDirectories(const std::string&s,const std::string&i)const{return safeId(s)&&safeId(i)&&mkdirs(itemPath(s,i)+"/segments");} bool DownloadStore::isCompleteSegment(const std::string&s,const std::string&i,std::uint64_t n)const{std::uint64_t z=0;return fileSize(segmentPath(s,i,n),z)&&z>0;} std::uint64_t DownloadStore::firstIncompleteSegment(const std::string&s,const DownloadItem&i)const{for(std::uint64_t n=0;n<i.hlsSegmentCount;n++)if(!isCompleteSegment(s,i.itemId,n))return n;return i.hlsSegmentCount;}
bool DownloadStore::saveManifest(const std::string&s,const DownloadItem&i,std::string*e)const{if(!safeId(s)||!safeId(i.itemId)||!atomic(manifestPath(s,i.itemId),serialize(i))){if(e)*e="manifest save failed";return false;}return true;} bool DownloadStore::loadManifest(const std::string&s,const std::string&id,DownloadItem&i,std::string*e)const{std::string b;if(!safeId(s)||!safeId(id)||!read(manifestPath(s,id),b)||!parse(b,i)){if(e)*e="invalid manifest";return false;}return true;}
bool DownloadStore::saveIndex(const std::string&s,const std::vector<DownloadItem>&v,std::string*e)const{if(!safeId(s)){if(e)*e="bad scope";return false;}std::string b="MFDI=1\n";std::set<std::string> seen;for(const auto&i:v)if(seen.insert(i.itemId).second)b+=i.itemId+"\n";if(!atomic(scopePath(s)+"/index.v1",b)){if(e)*e="index save failed";return false;}return true;} bool DownloadStore::loadIndex(const std::string&s,std::vector<DownloadItem>&v,std::string*e)const{std::string b;if(!read(scopePath(s)+"/index.v1",b)||b.rfind("MFDI=1\n",0)){if(e)*e="invalid index";return false;}std::vector<DownloadItem> loaded;std::set<std::string> seen;size_t p=7;while(p<b.size()){size_t z=b.find('\n',p);std::string id=b.substr(p,z-p);if(!id.empty()&&seen.insert(id).second){DownloadItem i;if(!loadManifest(s,id,i,e))return false;loaded.push_back(std::move(i));}if(z==std::string::npos)break;p=z+1;}v.insert(v.end(),loaded.begin(),loaded.end());return true;}
bool DownloadStore::rebuildIndex(const std::string&s,std::vector<DownloadItem>&v,std::string*e)const{DIR*d=opendir((scopePath(s)+"/items").c_str());if(!d){if(e)*e="no items";return false;}std::vector<DownloadItem> rebuilt;std::set<std::string> seen;dirent*x;while((x=readdir(d))){if(x->d_name[0]=='.'||!seen.insert(x->d_name).second)continue;DownloadItem i;if(loadManifest(s,x->d_name,i,nullptr))rebuilt.push_back(std::move(i));}closedir(d);if(!saveIndex(s,rebuilt,e))return false;v.insert(v.end(),rebuilt.begin(),rebuilt.end());return true;} bool DownloadStore::validateCompletedDownload(const std::string&s,const DownloadItem&i,std::string*e)const{if(i.hlsStorage){if(!i.hlsSegmentCount)return false;for(std::uint64_t k=0;k<i.hlsSegmentCount;k++)if(!isCompleteSegment(s,i.itemId,k)){if(e)*e="missing or empty segment";return false;}return true;}if(i.expectedSize==0||i.chunkSize==0)return false;std::uint64_t total=0,n=chunkCount(i.expectedSize,i.chunkSize);for(std::uint64_t k=0;k<n;k++){std::uint64_t z;if(!fileSize(chunkPath(s,i.itemId,k),z)||z!=chunkLength(i.expectedSize,k,i.chunkSize)){if(e)*e="missing or wrong-sized chunk";return false;}total=saturatingAdd(total,z);}if(total!=i.expectedSize){if(e)*e="total mismatch";return false;}return true;}
bool DownloadStore::reconcile(const std::string&s,DownloadItem&i,std::string*e)const{if(i.hlsStorage){std::uint64_t got=0;for(std::uint64_t k=0;k<i.hlsSegmentCount;k++){std::uint64_t z=0;if(!fileSize(segmentPath(s,i.itemId,k),z)||!z)break;got=saturatingAdd(got,z);}i.downloadedBytes=got;if(validateCompletedDownload(s,i,nullptr)){if(i.state!=DownloadState::UpdateAvailable&&i.state!=DownloadState::LocalOnly)i.state=DownloadState::Complete;}else if(i.state==DownloadState::Downloading)i.state=DownloadState::Queued;return saveManifest(s,i,e);}std::uint64_t got=0,n=chunkCount(i.expectedSize,i.chunkSize);for(std::uint64_t k=0;k<n;k++){std::uint64_t z=0,need=chunkLength(i.expectedSize,k,i.chunkSize);if(fileSize(chunkPath(s,i.itemId,k),z)){if(z!=need){if(e)*e="bad completed chunk";return false;}got=saturatingAdd(got,z);continue;}if(fileSize(chunkPath(s,i.itemId,k,true),z)){if(z>need){std::remove(chunkPath(s,i.itemId,k,true).c_str());z=0;}got=saturatingAdd(got,z);break;}break;}i.downloadedBytes=got;if(validateCompletedDownload(s,i,nullptr)){if(i.state!=DownloadState::UpdateAvailable&&i.state!=DownloadState::LocalOnly)i.state=DownloadState::Complete;}else if(i.state==DownloadState::Downloading)i.state=DownloadState::Queued;return saveManifest(s,i,e);}
bool DownloadStore::removePartialBytes(const std::string&s,const std::string&id,std::string*e)const{if(!safeId(s)||!safeId(id)){if(e)*e="unsafe id";return false;}for(const char *dir:{"chunks","segments"}){DIR*d=opendir((itemPath(s,id)+"/"+dir).c_str());if(!d)continue;dirent*x;while((x=readdir(d))){std::string n=x->d_name;if((std::string(dir)=="chunks"?n.rfind("chunk-",0)==0:true)&&(n.size()>4&&(n.rfind(".bin")==n.size()-4||n.rfind(".part")==n.size()-5)))std::remove((itemPath(s,id)+"/"+dir+"/"+n).c_str());}closedir(d);}return true;}
bool DownloadStore::removeItem(const std::string&s,const std::string&id,std::string*e)const{if(!safeId(s)||!safeId(id)){if(e)*e="unsafe id";return false;}DownloadItem i;loadManifest(s,id,i,nullptr);for(std::uint64_t k=0;k<chunkCount(i.expectedSize,i.chunkSize);++k){std::remove(chunkPath(s,id,k).c_str());std::remove(chunkPath(s,id,k,true).c_str());}for(std::uint64_t k=0;k<i.hlsSegmentCount;k++){std::remove(segmentPath(s,id,k).c_str());std::remove(segmentPath(s,id,k,true).c_str());}std::remove(manifestPath(s,id).c_str());::rmdir((itemPath(s,id)+"/chunks").c_str());::rmdir((itemPath(s,id)+"/segments").c_str());::rmdir(itemPath(s,id).c_str());return true;}
}
