#!/bin/sh
set -eu

# -------------------------------------------------------------------
# tools/make-dev-update.sh — Stage an offline OTA test
#
# Usage: tools/make-dev-update.sh <version> [tarball] [outdir]
#   version   — semver string, e.g. "0.9.0"
#   tarball   — path to MiyooFin.tar.gz (default: output/release/MiyooFin.tar.gz)
#   outdir    — staging directory (default: output/dev-update/)
# -------------------------------------------------------------------

VERSION="${1:?Usage: tools/make-dev-update.sh <version> [tarball] [outdir]}"
TARBALL="${2:-output/release/MiyooFin.tar.gz}"
OUTDIR="${3:-output/dev-update}"

if [ ! -f "$TARBALL" ]; then
    echo "ERROR: tarball not found: $TARBALL"
    echo "Build a release first, or pass the tarball path explicitly."
    exit 1
fi

mkdir -p "$OUTDIR"

# Copy the tarball into outdir
cp "$TARBALL" "$OUTDIR/MiyooFin-${VERSION}.tar.gz"

# Compute sha256 and byte size
SHA=$(sha256sum "$OUTDIR/MiyooFin-${VERSION}.tar.gz" | cut -d' ' -f1)
SIZE=$(wc -c < "$OUTDIR/MiyooFin-${VERSION}.tar.gz" | tr -d ' ')

# Get the real (absolute) path to the copied tarball
TARBALL_REAL=$(cd "$OUTDIR" && realpath "MiyooFin-${VERSION}.tar.gz")

# Write manifest.json
cat > "$OUTDIR/manifest.json" <<EOF
{
    "name": "MiyooFin",
    "version": "${VERSION}",
    "tag": "v${VERSION}",
    "min_version": "0.1.0",
    "published_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "notes": "Dev build ${VERSION}",
    "assets": {
        "tar_gz": {
            "url": "file://${TARBALL_REAL}",
            "sha256": "${SHA}",
            "size": ${SIZE}
        }
    }
}
EOF

# Get the real (absolute) path to the manifest
MANIFEST_REAL=$(cd "$OUTDIR" && realpath "manifest.json")

# Write update-dev-url.txt
cat > "$OUTDIR/update-dev-url.txt" <<EOF
# Dev update manifest override (auto-generated by make-dev-update.sh)
file://${MANIFEST_REAL}
EOF

echo ""
echo "=== Dev update staged in ${OUTDIR}/ ==="
echo ""
echo "Files created:"
echo "  ${OUTDIR}/MiyooFin-${VERSION}.tar.gz  (${SIZE} bytes, sha256 ${SHA})"
echo "  ${OUTDIR}/manifest.json"
echo "  ${OUTDIR}/update-dev-url.txt"
echo ""
echo "To test on device, copy these files:"
echo "  scp ${OUTDIR}/update-dev-url.txt  root@<device>:/mnt/SDCARD/App/MiyooFin/"
echo "  scp ${OUTDIR}/manifest.json       root@<device>:/mnt/SDCARD/App/MiyooFin/"
echo "  scp ${OUTDIR}/MiyooFin-${VERSION}.tar.gz root@<device>:/mnt/SDCARD/App/MiyooFin/update-download/"
echo ""
echo "Then relaunch MiyooFin and check for updates."
