#!/bin/sh
set -eu

# -------------------------------------------------------------------
# tools/make-dev-update.sh — Stage an offline OTA test
#
# Usage: tools/make-dev-update.sh <version> [tarball] [outdir]
#   version   — semver string, e.g. "0.9.0"
#   tarball   — path to MiyooFin.tar.gz (default: output/release/MiyooFin.tar.gz)
#   outdir    — staging directory (default: output/dev-update/)
# -------------------------------------------------------------------

VERSION="${1:?Usage: tools/make-dev-update.sh <version> [tarball] [outdir]}"
TARBALL="${2:-output/release/MiyooFin.tar.gz}"
OUTDIR="${3:-output/dev-update}"

# On-device app directory used by the scp flow below.  Override when the
# mount differs, e.g. DEVICE_APP_DIR=/mnt/SDCARD/App/MiyooFin tools/... .
DEVICE_APP_DIR="${DEVICE_APP_DIR:-/mnt/SDCARD/App/MiyooFin}"

if [ ! -f "$TARBALL" ]; then
    echo "ERROR: tarball not found: $TARBALL"
    echo "Build a release first, or pass the tarball path explicitly."
    exit 1
fi

mkdir -p "$OUTDIR"

# Copy the tarball into outdir
cp "$TARBALL" "$OUTDIR/MiyooFin-${VERSION}.tar.gz"

# Compute sha256 and byte size
SHA=$(sha256sum "$OUTDIR/MiyooFin-${VERSION}.tar.gz" | cut -d' ' -f1)
SIZE=$(wc -c < "$OUTDIR/MiyooFin-${VERSION}.tar.gz" | tr -d ' ')

# The manifest and the override must contain ON-DEVICE paths, not
# workstation paths: update-dev-url.txt is read verbatim from the device
# app dir and every file:// URL is opened as a device-local path
# (UpdateManager::workerRun), so a workstation absolute path can never
# resolve on the Miyoo and the update fails with "manifest not found" /
# "local tarball not found".  The tarball is staged in OUTDIR only so it
# can be copied to the device path below.
DEVICE_TARBALL_URL="file://${DEVICE_APP_DIR}/update-download/MiyooFin-${VERSION}.tar.gz"
DEVICE_MANIFEST_URL="file://${DEVICE_APP_DIR}/manifest.json"

# Write manifest.json
cat > "$OUTDIR/manifest.json" <<EOF
{
    "name": "MiyooFin",
    "version": "${VERSION}",
    "tag": "v${VERSION}",
    "min_version": "0.1.0",
    "published_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "notes": "Dev build ${VERSION}",
    "assets": {
        "tar_gz": {
            "url": "${DEVICE_TARBALL_URL}",
            "sha256": "${SHA}",
            "size": ${SIZE}
        }
    }
}
EOF

# Write update-dev-url.txt
cat > "$OUTDIR/update-dev-url.txt" <<EOF
# Dev update manifest override (auto-generated by make-dev-update.sh)
${DEVICE_MANIFEST_URL}
EOF

echo ""
echo "=== Dev update staged in ${OUTDIR}/ ==="
echo ""
echo "Files created:"
echo "  ${OUTDIR}/MiyooFin-${VERSION}.tar.gz  (${SIZE} bytes, sha256 ${SHA})"
echo "  ${OUTDIR}/manifest.json"
echo "  ${OUTDIR}/update-dev-url.txt"
echo ""
echo "Generated URLs (on-device paths):"
echo "  ${DEVICE_MANIFEST_URL}"
echo "  ${DEVICE_TARBALL_URL}"
echo ""
echo "To test on device, copy these files:"
echo "  scp ${OUTDIR}/update-dev-url.txt  root@<device>:${DEVICE_APP_DIR}/"
echo "  scp ${OUTDIR}/manifest.json       root@<device>:${DEVICE_APP_DIR}/"
echo "  scp ${OUTDIR}/MiyooFin-${VERSION}.tar.gz root@<device>:${DEVICE_APP_DIR}/update-download/"
echo ""
echo "Then relaunch MiyooFin and check for updates."
